feat(timepicker): add timepicker component
akveo/nebular pull request #2402
Opened 2020-06-03 15:08 UTC by maksim-karatkevich

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2020-06-04 15:25 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +              protected dateService: NbDateService<any>) {
Discuss generics

2020-06-04 15:26 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +      this.isTwelveHoursFormat).split(':');
Extract `:` into a property

2020-06-04 15:26 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +  subject$ = new Subject<NbSelectedTimePayload>();
Rename to something meaningful

2020-06-05 07:26 UTC, maksim-karatkevich commented on src/framework/moment/services/moment-date.service.ts
> +      this.datePipe.transform(currentTime, 'hh:mm:a') :
fixed

2020-06-05 07:44 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/_timepicker.component.theme.scss
> +      background-color: nb-theme(color-basic-300);
fixed

2020-06-05 08:00 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/model.ts
> +export enum TimepickerTypes {
added

2020-06-05 09:31 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/model.ts
> +export const timeValues: string[] = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09',
Added calendar-time-model.service.ts

2020-06-05 09:34 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +      this.isTwelveHoursFormat).split(':');
fixed

2020-06-05 09:35 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +  subject$ = new Subject<NbSelectedTimePayload>();
fixed

2020-06-05 09:38 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/timepicker.component.scss
> +  height: 26.1875rem;
removed property

2020-06-05 11:14 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +              protected dateService: NbDateService<any>) {
fixed

2020-06-05 11:14 UTC, maksim-karatkevich commented on src/framework/theme/components/timepicker/_timepicker.component.theme.scss
> +  .list-item {
fiexed

2020-07-13 11:00 UTC, yggg commented on src/playground/with-layout/timepicker/timepicker-example.scss
> +  text-transform: uppercase;
We don't use absolute values. And why it's set here?

2020-07-23 11:00 UTC, yggg commented on src/framework/theme/components/timepicker/model.ts
> +}
Same as above

2020-07-23 11:00 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker-cell.component.ts
> +    if (this.element) {
TODO: SSR, Check for scroll service in cdk

2020-07-23 11:01 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker-cell.component.ts
> +  @Input() type: NbTimepickerTypes;
Remove this along with `NbTimepickerTypes` enum

2020-07-23 11:03 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.html
> +    <ng-container *ngIf="!singleColumn; else fullTimeHeadersBlock">
Please, remove negation from the if expression and swap if/else blocks. It would be much easier to read.

2020-07-23 11:04 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.html
> +    <ng-container *ngIf="!singleColumn; else fullTimeColumnBlock">
same as above

2020-07-23 11:08 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +  trackByTimeValues(index, item): any {
`item: TimeOptions`

2020-07-23 11:10 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.component.ts
> +      return range(23, (v: number) => {
23 or 24?

2020-07-23 11:13 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +   * @docs-private
You don't need `@docs-private` on protected methods

2020-07-23 11:13 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +  protected overlayOffset = 8;
`@Input`

2020-07-23 11:13 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +    this.subscribeOnInputChange();
move to OnInit

2020-07-23 11:15 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +    this.input.placeholder = this.timepicker.timeFormat;
Is the placeholder a design requirement? Won't it override user defined placeholder?

2020-07-23 11:15 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +    }
to discuss

2020-07-23 11:17 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker.directive.ts
> +    this.timepicker.onSelectTime.subscribe((value: NbSelectedTimePayload<D>) => {
`takeUntil(this.destroy$)`

2020-07-23 11:18 UTC, yggg commented on src/framework/theme/styles/themes/_mapping.scss
> +  timepicker-hover-background-color: color-basic-300,
to discuss

2020-07-23 11:18 UTC, yggg commented on src/playground/with-layout/datepicker/date-timepicker-showcase.component.ts
> +          [title]="'Title'"
`title="Title"`. Do we need to specify it?

2020-07-23 11:19 UTC, yggg commented on src/playground/with-layout/datepicker/date-timepicker-single-column.component.ts
> +          [title]="'Title'"
`title="Title"`

2020-09-01 18:17 UTC, yggg requested changes
Also, check how date-timepicker looks with `size` set to `large`

2020-09-01 18:17 UTC, yggg commented on src/framework/theme/styles/themes/_mapping.scss
> +  timepicker-basic-color: border-basic-color-3,
basic -> border

2020-09-01 18:17 UTC, yggg commented on src/framework/theme/styles/themes/_mapping.scss
> +  timepicker-text-hint-padding: 0.625rem,
look where the variable is used and rename accordingly

2020-09-08 21:56 UTC, yggg requested changes

2020-09-08 21:56 UTC, yggg commented on src/framework/theme/components/datepicker/date-timepicker.component.ts
> +    if (this.picker.cd) {
remove if + make cd public in the picker component

2020-09-08 21:56 UTC, yggg commented on src/framework/theme/components/datepicker/calendar-with-time.component.ts
> +          <ng-container [ngTemplateOutlet]="timepicker.portal.templateRef"></ng-container>
Since we have portal in the `nb-timepicker`, let's use `nbPortalOutlet` instead of `ngTemplateOutlet`

2020-09-08 21:56 UTC, yggg commented on src/framework/theme/styles/themes/_mapping.scss
> +  timepicker-active-text-color: text-control-color,
`timepicker-cell`?

2020-09-08 21:56 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker-cell.component.ts
> +  scrollToElement() {
protected

2020-09-08 21:56 UTC, yggg commented on src/framework/theme/components/timepicker/timepicker-cell.component.ts
> +      this.valueContainerElement.nativeElement.scrollIntoView({block: 'center'});
Shouldn't we scroll outside Angular?

2020-09-09 15:06 UTC, yggg approved these changes

2020-09-10 07:39 UTC, merged

2020-09-11 07:18 UTC, murbanowicz commented
When is it suppose to be released? I cannot find any demo or so.