fix(datepicker): made adjustment customizable (#2455)
akveo/nebular pull request #2806
Opened 2021-08-03 10:27 UTC by evtkhvch

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

Disable the fact that the overlay with the picker changes position if it doesn't fit into the screen

<img width="553" alt="Screenshot 2021-08-03 at 13 22 01" src="https://user-images.githubusercontent.com/33560032/128000248-bd8c2ed9-6077-4dfe-8f87-940b2641ced4.png">
<img width="1015" alt="Screenshot 2021-08-03 at 13 22 35" src="https://user-images.githubusercontent.com/33560032/128000268-0fc4f92a-2e43-43ba-b295-d991613edcd9.png">

2021-08-03 10:46 UTC, yggg requested changes

2021-08-03 10:46 UTC, yggg commented on src/framework/theme/components/datepicker/datepicker.component.ts
> +  NbAdjustment, NbAdjustmentValues,
Add new line

2021-08-03 10:46 UTC, yggg commented on src/framework/theme/components/datepicker/datepicker.component.ts
> +  static ngAcceptInputType_adjustment: NbAdjustmentValues;
I think we don't need `static ngAcceptInputType_adjustment: NbAdjustmentValues;`. We use the `static ngAcceptInputType_` thing only when a property type differs from what the user can enter. Mostly we use it for the boolean inputs which could be used without a value, e.g. `<my-component booleanInput>`. Here the value of `booleanInput` is `undefined`, but the type on the property says it should be boolean, and Angular treat it like an error. With the `static ngAcceptInputType_booleanInput` we could overwrite type from the property with `boolean | undefined` to support usage without a value.

2021-08-03 12:40 UTC, evtkhvch commented on src/framework/theme/components/datepicker/datepicker.component.ts
> +  NbAdjustment, NbAdjustmentValues,
done

2021-08-06 14:06 UTC, yggg approved these changes

2021-08-06 14:07 UTC, merged