feat(tabset): template tab label
akveo/nebular pull request #2829
Opened 2021-08-16 12:27 UTC by evtkhvch

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2021-09-16 14:55 UTC, yggg requested changes

2021-09-16 14:55 UTC, yggg commented on src/framework/theme/components/tabset/tab-label.ts
> +  selector: '[nb-tab-label], [nbTabLabel]',
```suggestion
  selector: '[nbTabLabel]',
```

2021-09-16 14:55 UTC, yggg commented on src/framework/theme/components/tabset/tab-label.ts
> +import { CdkPortal } from '@angular/cdk/portal';
```suggestion
import { NbPortal } from '../cdk/..';
```

2021-09-16 14:55 UTC, yggg commented on src/framework/theme/components/tabset/tab-content.ts
> +}
Remove. Let's always use implicit content.

2021-09-20 13:26 UTC, evtkhvch commented on src/framework/theme/components/tabset/tab-label.ts
> +  selector: '[nb-tab-label], [nbTabLabel]',
done

2021-11-08 12:21 UTC, yggg requested changes

2021-11-08 12:21 UTC, yggg commented on src/framework/theme/components/tabset/tabset.component.ts
> +            <ng-template [cdkPortalOutlet]="tab.templateLabel"></ng-template>
Use `*ngTemplateOutlet` instead of portals. And then revert `src/framework/theme/components/cdk/*` changes.

2021-11-08 12:21 UTC, yggg commented on src/framework/theme/components/tabset/tabset.component.ts
> +  protected _templateLabel: NbTabLabelDirective;
Use property as there is no additional logic in accessors.

2021-11-08 12:21 UTC, yggg commented on src/framework/theme/components/tabset/tab-label.ts
> +export const NB_TAB_LABEL = new InjectionToken<NbTabLabelDirective>('NbTabLabel');
Why don't use `NbTabLabelDirective` class directly?

2021-11-08 16:07 UTC, yggg requested changes

2021-11-08 16:07 UTC, yggg commented on src/framework/theme/components/tabset/tabset.component.ts
> +  @ContentChild(NbTabLabelDirective, { read: TemplateRef }) templateLabel: TemplateRef<any> | undefined;
```suggestion
  @ContentChild(NbTabLabelDirective, { read: TemplateRef }) titleTemplate: TemplateRef<any> | undefined;
```

2021-11-08 16:07 UTC, yggg commented on src/framework/theme/components/tabset/tab-label.ts
> +export class NbTabLabelDirective {}
Let's change label to title as we reference it in tab object.
```suggestion
export class NbTabTitleDirective {}
```

2021-11-08 16:08 UTC, yggg requested changes
And let's add an example to the docs

2021-11-15 16:03 UTC, yggg approved these changes

2021-11-15 16:21 UTC, yggg approved these changes

2021-11-16 08:34 UTC, yggg approved these changes

2021-11-16 08:34 UTC, merged