feat(tooltip): disable the display of the tooltip
akveo/nebular pull request #2841
Opened 2021-08-23 14:19 UTC by evtkhvch

### Please read and mark the following check list before creating a pull request:

 - [] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2021-09-14 13:18 UTC, yggg requested changes
Move disabled logic into `NbDynamicOverlayHandler`

2021-09-14 13:18 UTC, yggg commented on src/framework/theme/components/tooltip/tooltip.directive.ts
> +  private _disabled = false;
protected

2021-09-15 13:04 UTC, evtkhvch commented on src/framework/theme/components/tooltip/tooltip.directive.ts
> +  private _disabled = false;
done

2021-11-08 12:14 UTC, yggg submitted a review, later dismissed

2021-11-08 14:22 UTC, yggg approved these changes

2021-11-08 15:04 UTC, merged