feat(select, autocomplete): ability to override options width
akveo/nebular pull request #2874
Opened 2021-09-13 11:17 UTC by evtkhvch

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

Closes: #2638

- add `NbSelectComponent.optionsWidth` property
- add `NbAutocompleteComponent.optionsWidth` property

2021-09-14 12:03 UTC, yggg requested changes

2021-09-14 12:03 UTC, yggg commented on src/framework/theme/components/select/select.component.ts
> +  private _optionsWidth: number | undefined;
Move above to the get/set declarations

2021-09-14 12:03 UTC, yggg commented on src/framework/theme/components/autocomplete/autocomplete.component.ts
> +  private _optionsWidth: number | undefined;
Move to the get/set declaration

2021-09-14 17:04 UTC, evtkhvch commented on src/framework/theme/components/select/select.component.ts
> +  private _optionsWidth: number | undefined;
done

2021-09-14 17:04 UTC, evtkhvch commented on src/framework/theme/components/autocomplete/autocomplete.component.ts
> +  private _optionsWidth: number | undefined;
done

2021-11-08 10:49 UTC, yggg approved these changes

2021-11-08 11:04 UTC, merged