add search for component list
akveo/nebular pull request #2939
Opened 2021-11-10 12:27 UTC by sokol147

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves: add search for component list

2021-11-12 11:11 UTC, yggg requested changes

2021-11-12 11:11 UTC, yggg commented on src/app/components-link.directive.ts
> +  constructor(private el: ElementRef, private componentsListSearchService: ComponentsListSearchService) {}
Order class members in a following way:
private members
public undecorated
public decorated
constructor
lifecycle methods
own methods

2021-11-12 11:11 UTC, yggg commented on src/app/components-link.directive.ts
> +  public ngOnInit(): void {
```suggestion
  ngOnInit(): void {
```

2021-11-12 11:11 UTC, yggg commented on src/app/components-link.directive.ts
> +      .subscribe();
No empty `subscribe`s

2021-11-12 11:11 UTC, yggg commented on src/app/components-link.directive.ts
> +            this.el.nativeElement.classList.add('focus');
Use Angular API to access DOM API, e.g. modify classes. It looks like it could be refactored to use `HostBinding` to `focus` class.

2021-11-12 11:11 UTC, yggg commented on src/app/components-link.directive.ts
> +  public ngOnDestroy() {
```suggestion
  ngOnDestroy() {
```

2021-11-12 11:11 UTC, yggg commented on src/app/components-list.service.ts
> +  public componentsList$: Observable<ComponentLink[]> = this.inputSearch$.pipe(
If members must be public, then remove access modifiers. Otherwise, make it private.

2021-11-12 11:11 UTC, yggg commented on src/app/app.component.ts
> +    }
Extract huge properties access lines into a variables with descriptive names, for example:
`this.componentsListSearchService.activeElementIndex$.value - 1` -> `prevElementIndex`
Intead of `if` use `this.componentsListSearchService.activeElementIndex$.next(Math.max(prevElementIndex, 0))`.

2021-11-12 11:15 UTC, yggg requested changes
And add escape key handler to close list overlay

2021-11-15 09:57 UTC, sokol147 commented on src/app/app.component.scss
> +
changed to .component-list-wrapper

2021-11-15 10:15 UTC, sokol147 commented on src/app/components-list/components-list.component.scss
> +  &.focus {
changed to `selected`

2021-11-15 11:13 UTC, sokol147 commented on src/app/app.component.ts
> +        this.componentSearch.nativeElement.blur();
removed

2021-11-16 08:56 UTC, sokol147 commented on src/app/app.component.ts
> +    fromEvent(this.componentSearch.nativeElement, 'keyup')
add method for key up and enter

2021-11-22 12:59 UTC, yggg approved these changes

2021-11-22 13:21 UTC, merged