feat(deploy docs): Copy docs of existing version from gh-pages
akveo/nebular pull request #2950
Opened 2021-11-22 07:45 UTC by katebatura

### Please read and mark the following check list before creating a pull request:

 - [X] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [X] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

Copy docs of existing version from `gh-pages` instead of building them again.

2021-11-24 08:42 UTC, yggg requested changes

2021-11-26 08:22 UTC, katebatura commented on tools/deploy-docs/build-docs.ts
> +}
This function isn't used anymore.

2021-11-26 13:39 UTC, yggg requested changes

2021-11-26 13:39 UTC, yggg commented on .github/workflows/deploy-docs.yml
> +
Remove unnecessary new line

2021-11-26 13:39 UTC, yggg commented on .github/workflows/deploy-docs.yml
> +
Remove unnecessary new line

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/versions.json
> +    "checkoutTarget": "774803db",
Could we change it to `8.0.x`?

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +  const builtVersions: { hash; path }[] = await checkBuiltVersions();
```suggestion
  log('Get build versions from gh-pages branch');
  await copyToBuildDir(MASTER_BRANCH_DIR, GH_PAGES_DIR);
  await checkoutVersion('gh-pages', GH_PAGES_DIR);
  const builtVersions: { hash; path }[] = await checkBuiltVersions();
```

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +  console.log('Built versions in gh-pages:', builtVersions);
Use `log` and move to the main function after `checkBuiltVersions` call.

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +async function createFileWithCommitHash(path: string, projectDir: string) {
```suggestion
async function addCommitHash(path: string, projectDir: string) {
```
To conform to already existing `addVersionNameToPackageJson` and `addVersionTs`.

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +  const { stdout: currentHash } = await promisify(exec)('git rev-parse HEAD', { cwd: projectDir });
Extract into getStdout function.

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +  const correspondingVersion = builtVersions.find((item) => currentHash === item.hash);
```suggestion
  const existInGhPages = builtVersions.find((item) => currentHash === item.hash);
```

2021-11-26 13:39 UTC, yggg commented on tools/deploy-docs/build-docs.ts
> +async function copyExistingDocs(version, correspondingVersionPath, distDir) {
```suggestion
async function copyFromGhPages(version, correspondingVersionPath, distDir) {
```

2021-12-02 13:46 UTC, yggg approved these changes

2021-12-02 13:47 UTC, yggg approved these changes

2021-12-02 14:29 UTC, merged